/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./../components/layout/AppLayout/AppLayout.vue')['default']
    Button: typeof import('./../components/ui/Button/Button.vue')['default']
    Card: typeof import('./../components/ui/Card/Card.vue')['default']
    DataChart: typeof import('./../components/business/DataChart/DataChart.vue')['default']
    DeviceStatus: typeof import('./../components/business/DeviceStatus/DeviceStatus.vue')['default']
    Dialog: typeof import('./../components/ui/Dialog/Dialog.vue')['default']
    ElementTest: typeof import('./../components/test/ElementTest.vue')['default']
    Footer: typeof import('./../components/layout/Footer/Footer.vue')['default']
    Header: typeof import('./../components/layout/Header/Header.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./../components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./../components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./../components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./../components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./../components/icons/IconTooling.vue')['default']
    Input: typeof import('./../components/ui/Input/Input.vue')['default']
    LabelEditor: typeof import('./../components/business/LabelEditor/LabelEditor.vue')['default']
    PrintQueue: typeof import('./../components/business/PrintQueue/PrintQueue.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./../components/ui/Select/Select.vue')['default']
    Sidebar: typeof import('./../components/layout/Sidebar/Sidebar.vue')['default']
    Table: typeof import('./../components/ui/Table/Table.vue')['default']
    TheWelcome: typeof import('./../components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./../components/WelcomeItem.vue')['default']
  }
}
